apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto-app
  template:
    metadata:
      labels:
        app: auto-app
    spec:
      containers:
      - name: auto-container
        image: auto-k8s-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000